
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 12 18:11:11 COT 2022
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 21;
  public static final int T_Dato = 4;
  public static final int Llave_c = 28;
  public static final int Op_booleano = 24;
  public static final int Llave_a = 27;
  public static final int If = 6;
  public static final int Else = 7;
  public static final int Corchete_c = 30;
  public static final int Corchete_a = 29;
  public static final int graficarPoligono = 14;
  public static final int While = 9;
  public static final int Int = 36;
  public static final int Division = 19;
  public static final int Cadena = 5;
  public static final int Parentesis_c = 26;
  public static final int graficarCuadrado = 11;
  public static final int Parentesis_a = 25;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int P_coma = 32;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int graficarCirculo = 13;
  public static final int Op_atribucion = 22;
  public static final int ERROR = 35;
  public static final int Do = 8;
  public static final int Op_logico = 20;
  public static final int graficarTriangulo = 12;
  public static final int Identificador = 33;
  public static final int Resta = 17;
  public static final int Multiplicacion = 18;
  public static final int Op_incremento = 23;
  public static final int Numero = 34;
  public static final int Suma = 16;
  public static final int Main = 31;
  public static final int Igual = 15;
  public static final int Comillas = 3;
}

